Repository DoDreamTeam/Frontend, pull requests merged in 2024-10, with the labels that each got.

#6 [디자인] 메인 페이지
  package-lock.json
  package.json
  src/App.js
  src/components/main/Banner.jsx
  src/components/main/BestBook.jsx
  src/components/main/BestBookList.jsx
  src/components/main/BestStudy.jsx
  src/components/main/BestStudyList.jsx
  src/components/main/TotalSearch.jsx
  src/components/notification/NotificationMenu.jsx
  src/components/ui/BookCard.jsx
  src/components/ui/SearchInput.jsx
  src/components/ui/StudyCard.jsx
  src/pages/Main.jsx
Labels: 🎨 Html/css

#8 [프로젝트 세팅 ] CRA에서 Vite로 마이그레이션
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/index.jsx
  vite.config.js
Labels: ⚙️ Setting

#10 [디자인] 문제집 메인 페이지
  src/components/bookmain/BookBanner.jsx
  src/components/bookmain/BookList.jsx
  src/components/bookmain/BookSearch.jsx
  src/hooks/usePagination.jsx
  src/pages/BookMain.jsx
Labels: 🎨 Html/css

#12 [디자인] 마이페이지 메인 페이지
  package-lock.json
  package.json
  src/components/layouts/Header.jsx
  src/components/mypage/MyActiivityCalendar.jsx
  src/components/mypage/MyProfile.jsx
  src/pages/MyPage.jsx
Labels: 🎨 Html/css

#14 [디자인] 스터디 메인 페이지
  src/components/studymain/StudyBanner.jsx
  src/components/studymain/StudyList.jsx
  src/components/studymain/StudySearch.jsx
  src/pages/StudyMain.jsx
Labels: 🎨 Html/css

#16 [기능 개발] 소셜 로그인 연동 (Kakao, Naver, Google)
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/assets/google.png
  src/assets/kakao.png
  src/assets/naver.png
  src/components/auth/LoginButton.jsx
  src/components/auth/LogoutButton.jsx
  src/components/layouts/Header.jsx
  src/hooks/useAuth.jsx
  src/hooks/useModal.jsx
  src/index.jsx
  src/pages/OAuthVertification.jsx
  src/pages/index.js
  src/utils/cookieUtils.js
Labels: ✨ Feature, 🎨 Html/css

#19 [기능개발-마이페이지] 프로필 조회 연동
  src/App.jsx
  src/components/layouts/Header.jsx
  src/components/mypage/MyActiivityCalendar.jsx
  src/components/mypage/MyProfile.jsx
  src/hooks/useUser.jsx
  src/pages/MyPage.jsx
Labels: ✨ Feature

#20 [기능 개발 - 메인페이지] 메인페이지 api 연동
  package-lock.json
  package.json
  src/App.jsx
  src/api/api.js
  src/components/main/BestBookList.jsx
  src/components/main/BestStudyList.jsx
  src/components/main/SearchResult.jsx
  src/components/main/TotalSearch.jsx
  src/components/ui/BookCard.jsx
  src/components/ui/StudyCard.jsx
  src/index.jsx
  src/pages/MainSearch.jsx
  src/pages/index.js
  src/utils/categoryUtils.js
Labels: ✨ Feature

#22 [기능 개발 - 문제집] 문제집 메인 페이지 api 연동
  src/components/bookmain/BookBanner.jsx
  src/components/bookmain/BookList.jsx
  src/components/bookmain/BookSearch.jsx
  src/components/ui/BookCard.jsx
  src/hooks/usePagination.jsx
  src/pages/BookMain.jsx
  src/utils/categoryUtils.js
Labels: ✨ Feature

#25 [기능 개발 - 문제집] 문제집 만들기 api 연동
  src/api/api.js
  src/components/createBook/CreateBookForm.jsx
  src/pages/BookMain.jsx
  src/pages/BookPageNoQuestion.jsx
  src/pages/CreateBook.jsx
  src/pages/OAuthVertification.jsx
Labels: ✨ Feature

#27 [기능 개발] 로그인 여부에 따른 접근 가능한 url 지정
  src/App.jsx
  src/components/authentication/ProtectedRoute.jsx
  src/context/AuthContext.jsx
Labels: ✨ Feature

#29 [기능 개발 - 인증] 유저 정보 전역적으로 받아오기
  src/components/auth/LogoutButton.jsx
  src/components/authentication/ProtectedRoute.jsx
  src/components/layouts/Header.jsx
  src/components/mypage/MyActiivityCalendar.jsx
  src/components/mypage/MyProfile.jsx
  src/context/UserProvider.jsx
  src/hooks/useUser.jsx
  src/index.jsx
  src/pages/MyPage.jsx
Labels: ✨ Feature
