Repository DoDreamTeam/Frontend, pull requests merged in 2024-11, with the labels that each got.

#33 [기능 개발 - 문제집] 특정 문제집의 메인페이지 문제 조회+검색
  src/App.jsx
  src/components/bookmain/BookList.jsx
  src/components/bookpage/BookInfo.jsx
  src/components/bookpage/QuestionList.jsx
  src/components/main/BestBookList.jsx
  src/components/ui/BookCard.jsx
  src/components/ui/BookmarkButton.jsx
  src/pages/BookPageWithQuestion.jsx
  src/pages/Main.jsx
  src/utils/evaluationUtils.js
  src/utils/formatDateUtils.js
Labels: ✨ Feature

#35 [기능 개발 - 문제집] 북마크 api 연동
  src/components/bookmain/BookList.jsx
  src/components/bookpage/BookInfo.jsx
  src/components/main/BestBookList.jsx
  src/components/mypage/MyPageBookmarkBooks.jsx
  src/components/ui/BookCard.jsx
  src/components/ui/BookmarkButton.jsx
  src/hooks/useAlert.jsx
Labels: ✨ Feature

#37 [기능 개발 - 마이페이지] 내가 푼 문제 페이지
  src/App.jsx
  src/components/mypage/BookLockToggle.jsx
  src/components/mypage/GetUser.jsx
  src/components/mypage/MyAnswers.jsx
  src/components/mypage/MyBookCommentLike.jsx
  src/components/mypage/MyPageBookmarkBooks.jsx
  src/components/mypage/MyPageBooks.jsx
  src/components/mypage/MyPageBooksAll.jsx
  src/components/mypage/MyProfile.jsx
  src/components/mypage/MyProfileMe.jsx
  src/pages/MyBooks.jsx
  src/pages/MyPage.jsx
  src/pages/MyQuestions.jsx
Labels: ✨ Feature

#39 [기능 개발 - 문제집] 특정 문제집 메인 페이지
  src/App.jsx
  src/components/bookmain/comment/BookCommentForm.jsx
  src/components/bookmain/comment/CommentList.jsx
  src/components/bookmain/comment/LikeButton.jsx
  src/components/bookpage/BookComment.jsx
  src/components/bookpage/BookInfo.jsx
  src/components/ui/Comment.jsx
  src/components/ui/CommentForm.jsx
  src/hooks/useModal.jsx
  src/pages/BookPageWithQuestion.jsx
  src/pages/EditBook.jsx
  src/pages/index.js
Labels: ✨ Feature

#41 [기능 개발 - 마이페이지] 참여 중 스터디 페이지 , 프로필 수정
  src/components/mypage/GetUser.jsx
  src/components/mypage/MyAnswers.jsx
  src/components/mypage/MyPageBookmarkBooks.jsx
  src/components/mypage/MyProfile.jsx
  src/components/mypage/MyProfileMe.jsx
  src/components/mypage/MyStudiesList.jsx
  src/components/mypage/MyStudyCommentLike.jsx
  src/context/UserProvider.jsx
  src/pages/MyQuestions.jsx
  src/pages/MyStudies.jsx
Labels: ✨ Feature

#43 [기능 개발 - 문제집] 문제집 수정 / 문제 CRUD api 연동
  src/components/bookpage/BookComment.jsx
  src/components/bookpage/BookInfo.jsx
  src/components/bookpage/QuestionList.jsx
  src/components/bookpage/comment/BookCommentForm.jsx
  src/components/bookpage/comment/CommentList.jsx
  src/components/bookpage/comment/LikeButton.jsx
  src/components/editBook/EditForm.jsx
  src/components/question/AddQuestionForm.jsx
  src/components/question/EditQuestionForm.jsx
  src/components/ui/Comment.jsx
  src/hooks/useAlert.jsx
  src/pages/AddQuestion.jsx
  src/pages/BookPageWithQuestion.jsx
  src/pages/EditBook.jsx
  src/pages/EditQuestion.jsx
Labels: ✨ Feature

#45 [기능 개발 - 마이페이지] 공부내역 기능 구현 , 페이지 이동 추가
  src/components/mypage/MyActiivityCalendar.jsx
  src/components/mypage/MyBookCommentLike.jsx
  src/components/mypage/MyPageBookmarkBooks.jsx
  src/components/mypage/MyPageBooks.jsx
  src/components/mypage/MyPageBooksAll.jsx
Labels: ✨ Feature

#48 [기능 개발 - 스터디] 스터디 답변 페이지 api 연동
  src/App.jsx
  src/components/mypage/MyAnswers.jsx
  src/components/mypage/MyBookCommentLike.jsx
  src/components/mypage/MyPageBooksAll.jsx
  src/components/mypage/MyStudyCommentLike.jsx
  src/components/study/StudyQuestion.jsx
  src/components/study/StudyQuestionComment.jsx
  src/components/study/comment/LikeButton.jsx
  src/components/study/comment/StudyComment.jsx
  src/components/study/comment/StudyCommentForm.jsx
  src/components/study/comment/StudyCommentList.jsx
  src/pages/StudyQuestionPage.jsx
Labels: ✨ Feature, 💠 Styles

#50 [기능 개발 - 스터디] 메인 화면 + 스터디 메인 화면
  src/components/main/BestStudyList.jsx
  src/components/studymain/StudyBanner.jsx
  src/components/studymain/StudyList.jsx
  src/components/studymain/StudySearch.jsx
  src/components/ui/StudyCard.jsx
  src/pages/StudyMain.jsx
  src/utils/statusUtils.js
Labels: ✨ Feature

#53 [기능 개발 - 문제집] 내 문제집에 추가 / 스터디에 추가 기능
  src/App.jsx
  src/components/addToStudy/SelectStudy.jsx
  src/components/bookpage/QuestionList.jsx
  src/components/bookpage/comment/CommentList.jsx
  src/components/editBook/EditForm.jsx
  src/components/question/AddQuestionForm.jsx
  src/components/question/EditQuestionForm.jsx
  src/components/questionEvaluate/AddModal.jsx
  src/components/questionEvaluate/AddToMyBooks.jsx
  src/components/ui/BookCard.jsx
  src/pages/AddToStudy.jsx
  src/pages/BookPage.jsx
  src/pages/BookPageNoQuestion.jsx
  src/pages/QuestionPage.jsx
  src/pages/index.js
Labels: ✨ Feature

#55 [기능 개발] notification 기능 api 연동
  src/components/layouts/Header.jsx
  src/components/notification/NotificationMenu.jsx
Labels: ✨ Feature

#59 [기능 개발 - 스터디] 스터디 메인 페이지, 스터디 방 메인 페이지, 공지사항
  src/App.jsx
  src/components/createStudy/CreateStudyForm.jsx
  src/components/studypage/Notice.jsx
  src/components/studypage/NoticeComment.jsx
  src/components/studypage/NoticeForm.jsx
  src/components/studypage/StudyInfo.jsx
  src/components/studypage/comment/CommentList.jsx
  src/components/studypage/comment/LikeButton.jsx
  src/components/studypage/comment/NoticeCommentForm.jsx
  src/components/ui/StudyCard.jsx
  src/pages/CreateStudy.jsx
  src/pages/StudyPage.jsx
Labels: ✨ Feature

#58 [버그 수정] 회원/비회원 구분 및 Modal 추가
  src/components/addToStudy/SelectStudy.jsx
  src/components/authentication/ProtectedRoute.jsx
  src/components/bookmain/BookList.jsx
  src/components/bookpage/QuestionList.jsx
  src/components/bookpage/comment/BookCommentForm.jsx
  src/components/bookpage/comment/CommentList.jsx
  src/components/createBook/CreateBookForm.jsx
  src/components/mypage/MyBookCommentLike.jsx
  src/components/questionEvaluate/AddModal.jsx
  src/components/questionEvaluate/SolveQuestionForm.jsx
  src/components/study/comment/StudyCommentList.jsx
  src/components/studymain/StudyList.jsx
  src/components/ui/Pagination.jsx
  src/hooks/useModal.jsx
  src/pages/MainSearch.jsx
  src/pages/QuestionPage.jsx
Labels: 🐞 Bugfix

#60 [기능 개발 - 스터디] 스터디 관리자 페이지 api 연동
  src/components/mypage/MyActiivityCalendar.jsx
  src/components/mypage/MyAnswers.jsx
  src/components/mypage/MyBookCommentLike.jsx
  src/components/mypage/MyPageBookmarkBooks.jsx
  src/components/mypage/MyPageBooks.jsx
  src/components/mypage/MyPageBooksAll.jsx
  src/components/mypage/MyProfile.jsx
  src/components/mypage/MyProfileMe.jsx
  src/components/mypage/MyStudiesList.jsx
  src/components/mypage/MyStudyCommentLike.jsx
  src/components/study/adminpage/StudyApplyMember.jsx
  src/components/study/adminpage/StudyInfoEdit.jsx
  src/components/study/adminpage/StudyMember.jsx
  src/components/study/adminpage/StudyNoticeEdit.jsx
  src/components/study/comment/StudyCommentList.jsx
  src/components/study/questionpage/StudyQuestion.jsx
  src/components/study/questionpage/StudyQuestionComment.jsx
  src/pages/StudyAdminPage.jsx
  src/pages/StudyQuestionPage.jsx
Labels: ✨ Feature

#63 [버그 수정 - 문제집] 특정 문제집 전체 조회 / 내가 푼 문제 제외 조회 수정 및 Alert 수정
  src/components/addToStudy/SelectStudy.jsx
  src/components/bookmain/BookList.jsx
  src/components/bookpage/BookInfo.jsx
  src/components/bookpage/QuestionList.jsx
  src/components/bookpage/comment/LikeButton.jsx
  src/components/bookpage/question/EvaluationButton.jsx
  src/components/bookpage/question/QuestionItem.jsx
  src/components/editBook/EditForm.jsx
  src/components/main/TotalSearch.jsx
  src/components/question/EditQuestionForm.jsx
  src/components/study/comment/LikeButton.jsx
  src/components/studypage/StudyInfo.jsx
  src/components/studypage/comment/LikeButton.jsx
  src/components/ui/BookmarkButton.jsx
  src/components/ui/DeleteConfirmModal.jsx
  src/components/ui/DeleteSuccessModal.jsx
  src/components/ui/EditSuccessModal.jsx
  src/components/ui/LoginRequestModal.jsx
  src/hooks/useAlert.jsx
Labels: 🐞 Bugfix

#64 [기능 개발 - 스터디] 스터디 메인 페이지 기능 연동 , 디자인
  src/App.jsx
  src/components/layouts/Header.jsx
  src/components/study/adminpage/StudyApplyMember.jsx
  src/components/study/adminpage/StudyInfoEdit.jsx
  src/components/study/adminpage/StudyMember.jsx
  src/components/study/adminpage/StudyNoticeEdit.jsx
  src/components/study/mainpage/StudyInfo.jsx
  src/components/study/mainpage/StudyNotice.jsx
  src/components/study/mainpage/StudyNoticeComment.jsx
  src/components/study/mainpage/StudyQuestionList.jsx
  src/components/study/mainpage/StudyQuestionSearch.jsx
  src/components/study/noticecomment/LikeButton.jsx
  src/components/study/noticecomment/NoticeComment.jsx
  src/components/study/noticecomment/NoticeCommentForm.jsx
  src/components/study/noticecomment/NoticeCommentList.jsx
  src/components/study/questionpage/StudyQuestionComment.jsx
  src/components/study/studycomment/LikeButton.jsx
  src/components/study/studycomment/StudyComment.jsx
  src/components/study/studycomment/StudyCommentForm.jsx
  src/components/study/studycomment/StudyCommentList.jsx
  src/components/ui/SearchInput.jsx
  src/pages/StudyAdminPage.jsx
  src/pages/StudyPage.jsx
Labels: ✨ Feature

#66 [CI/CD] 프론트 프로젝트 배포
  Dockerfile
  docker-compose.yml
  nginx.conf
Labels: 🤖 CI/CD
